In [1]:
import numpy as np

In [3]:
A = np.array([[1,1],[2,2],[0,0]])

In [6]:
u,s,v = np.linalg.svd(A)
print(u)
print(s)
print(v)
A2 = u[:,:2]
print(A2)

[[-0.4472136  -0.89442719  0.        ]
 [-0.89442719  0.4472136   0.        ]
 [ 0.          0.          1.        ]]
[3.16227766e+00 8.22677308e-17]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]
 [ 0.          0.        ]]


In [7]:
from sklearn.utils.extmath import randomized_svd

In [9]:
u,s,v = randomized_svd(A,n_components=2)
print(u)
print(s)
print(v)

[[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]
 [ 0.         -0.        ]]
[3.16227766e+00 1.62596948e-32]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
