In [9]:
import torch.nn as nn
import torch

In [2]:
linear = nn.Linear(5, 2)

# 全部参数初始化为0
nn.init.zeros_(linear.weight)
print(linear.weight)

# 全部参数初始化为1
nn.init.ones_(linear.weight)
print(linear.weight)

# 全部参数初始化为一个常数
nn.init.constant_(linear.weight, 10)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)
Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)


In [3]:
linear = nn.Linear(5, 2)

# 参数初始化为单位矩阵
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [4]:
linear = nn.Linear(5, 2)

# 参数初始化为按指定均值与标准差正态分布
nn.init.normal_(linear.weight, mean=0.0, std=1.0)
print(linear.weight)

Parameter containing:
tensor([[-0.2428, -0.4362,  0.1998,  1.4996, -0.0822],
        [ 1.2660, -0.3316, -0.2929, -1.5776,  0.7938]], requires_grad=True)


In [5]:
linear = nn.Linear(5, 2)

# 参数初始化为在区间内均匀分布
nn.init.uniform_(linear.weight, a=0, b=10)
print(linear.weight)

Parameter containing:
tensor([[9.5141, 5.8835, 0.1406, 4.9564, 1.4959],
        [4.0020, 4.6917, 6.1632, 1.4764, 6.4019]], requires_grad=True)


In [6]:
linear = nn.Linear(5, 2)

# Xavier正态分布初始化
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

# Xavier均匀分布初始化
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.8607,  0.3843,  0.0383,  0.6393,  0.2571],
        [-0.0219,  0.4950, -0.5018, -0.7979, -1.4181]], requires_grad=True)
Parameter containing:
tensor([[-0.2316, -0.8706, -0.5448, -0.5925, -0.2367],
        [ 0.6495, -0.8244, -0.2307,  0.8804,  0.1824]], requires_grad=True)


In [7]:
linear = nn.Linear(5, 2)

# Kaiming正态分布初始化
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

# Kaiming均匀分布初始化
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-4.8516e-03,  9.5083e-01,  1.3422e+00, -8.8469e-02,  5.8941e-05],
        [-1.3736e-01,  1.8376e-01, -1.1279e+00,  9.9314e-01,  7.2503e-01]],
       requires_grad=True)
Parameter containing:
tensor([[-0.3955, -0.9987, -0.9162, -0.8832,  0.4106],
        [ 1.0363,  0.9960,  0.4119, -0.4073, -0.4130]], requires_grad=True)


In [10]:
dropout = nn.Dropout(p=0.5)
x = torch.randint(1, 10, (10,), dtype=torch.float32)
print("Dropout前：", x)
print("Dropout后：", dropout(x))

Dropout前： tensor([2., 6., 3., 7., 9., 1., 6., 1., 2., 2.])
Dropout后： tensor([ 4.,  0.,  0., 14., 18.,  0., 12.,  0.,  0.,  0.])
