In [3]:
import torch

In [4]:
import torch



# 创建指定形状的张量，默认类型为float32

tensor1 = torch.Tensor(3, 2, 4)

print(tensor1)

print(tensor1.dtype)



# 也可以用来创建指定内容的张量

tensor2 = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

print(tensor2)

tensor([[[7.3425e+37, 4.5639e-41, 1.3946e-07, 0.0000e+00],
         [7.3591e+37, 4.5639e-41, 7.3425e+37, 4.5639e-41]],

        [[1.3946e-07, 0.0000e+00, 2.0319e-43, 0.0000e+00],
         [5.0054e-15, 3.0709e-41, 2.8190e+28, 4.5640e-41]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.3934e-07, 0.0000e+00, 7.4191e+37, 4.5639e-41]]])
torch.float32
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])


In [5]:
import numpy as np



# 创建标量张量

tensor1 = torch.tensor(10)

print(tensor1)



# 使用列表创建张量

tensor2 = torch.tensor([1, 2, 3])

print(tensor2)



# 使用numpy创建张量

tensor3 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

print(tensor3)

tensor(10)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [6]:
# 创建int32类型的张量

tensor1 = torch.IntTensor(2, 3)

tensor2 = torch.tensor([1, 2, 3], dtype=torch.int32)

print(tensor1)

print(tensor2)



# 元素类型不匹配则会进行类型转换

tensor1 = torch.IntTensor([1.1, 2.2, 3.6])

tensor2 = torch.tensor([3.1, 2.2, 1.6], dtype=torch.int32)

print(tensor1)

print(tensor2)



# 创建int64类型的张量

tensor1 = torch.LongTensor([1, 2, 3])

tensor2 = torch.tensor([1, 2, 3], dtype=torch.int64)

print(tensor1, tensor1.dtype)

print(tensor2, tensor1.dtype)



# 创建int16类型的张量

tensor1 = torch.ShortTensor(2, 2)

tensor2 = torch.tensor([1, 2, 3], dtype=torch.int16)

print(tensor1, tensor1.dtype)

print(tensor2, tensor1.dtype)



# 创建float32类型的张量

tensor1 = torch.FloatTensor([9, 8, 7])

tensor2 = torch.tensor([1, 2, 3], dtype=torch.float32)

print(tensor1, tensor1.dtype)

print(tensor2, tensor1.dtype)



# 创建float64类型的张量

tensor1 = torch.DoubleTensor(2, 3, 1)

tensor2 = torch.tensor([1, 2, 3], dtype=torch.float64)

print(tensor1)

print(tensor2)

tensor([[666143120,     21915, 666152112],
        [    21915,        80,         0]], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([3, 2, 1], dtype=torch.int32)
tensor([1, 2, 3]) torch.int64
tensor([1, 2, 3]) torch.int64
tensor([[0, 0],
        [0, 0]], dtype=torch.int16) torch.int16
tensor([1, 2, 3], dtype=torch.int16) torch.int16
tensor([9., 8., 7.]) torch.float32
tensor([1., 2., 3.]) torch.float32
tensor([[[6.9114e-310],
         [4.6504e-310],
         [4.6504e-310]],

        [[ 0.0000e+00],
         [ 0.0000e+00],
         [4.6504e-310]]], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float64)


In [7]:
# torch.arange(start, end, step) 在区间[start,end)中创建步长为step的张量
tensor1 = torch.arange(10, 30, 2)
print(tensor1)

# torch.arange(end) 创建区间为[0,end)，步长为1的张量
tensor2 = torch.arange(6)
print(tensor2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
tensor([0, 1, 2, 3, 4, 5])


In [8]:
# torch.linspace(start, end, steps) 在区间按元素数量创建张量
tensor1 = torch.linspace(10, 30, 5)
print(tensor1)

tensor([10., 15., 20., 25., 30.])


In [9]:
# torch.logspace(start, end, steps, base) 在区间[start,end]之间生成steps个数，并以base为底，区间内的数为指数创建张量
tensor1 = torch.logspace(1, 3, 3, 2)
print(tensor1)

tensor([2., 4., 8.])


In [10]:
# torch.zeros(size) 创建指定形状的全0张量
tensor1 = torch.zeros(2, 3)
print(tensor1)

# torch.ones_like(input) 创建与给定张量形状相同的全1张量
tensor2 = torch.ones_like(tensor1)
print(tensor2)

# torch.full(size,fill_value) 创建指定形状的按指定值填充的张量
tensor1 = torch.full((2, 3), 6)
print(tensor1)

# torch.empty_like(input) 创建与给定张量形状相同的未初始化的张量
tensor2 = torch.empty_like(tensor3)
print(tensor2)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[6, 6, 6],
        [6, 6, 6]])
tensor([[139888942263488, 139888942263488,  94124875979048],
        [            209,  94124874438512, 139888942263264],
        [ 94124875979048,              24,  94124875978632]])


In [11]:
# torch.eye(n) 创建n*n的单位矩阵
tensor1 = torch.eye(3)
print(tensor1)

# torch.eye(n, m) 按指定的行和列创建
tensor2 = torch.eye(3, 4)
print(tensor2)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


In [12]:
# torch.rand(size) 创建在[0,1)上均匀分布的，指定形状的张量
tensor1 = torch.rand(2, 3)
print(tensor1)

# torch.rand_like(input) 创建在[0,1)上均匀分布的，与给定张量形状相同的张量
tensor2 = torch.randint_like(tensor1, 1, 10)
print(tensor2)

# torch.randn(size) 创建标准正态分布的，指定形状的张量
tensor1 = torch.randn(4, 2)
print(tensor1)

# torch.normal(mean,std,size) 创建自定义正态分布的，指定形状的张量。mean为均值，std为标准差
tensor2 = torch.normal(5, 1, tensor1.shape)
print(tensor2)

tensor([[0.7275, 0.0049, 0.3663],
        [0.3122, 0.4657, 0.7128]])
tensor([[3., 7., 6.],
        [8., 3., 1.]])
tensor([[ 1.5891,  0.1355],
        [ 0.3104, -0.0958],
        [-1.6130, -1.0567],
        [ 0.0360, -0.8481]])
tensor([[6.7606, 3.7889],
        [4.8443, 5.7884],
        [2.8639, 4.7546],
        [3.6005, 4.3625]])


In [13]:
# torch.randperm(n) 生成从0到n-1的随机排列
tensor1 = torch.randperm(10)
print(tensor1)

tensor([8, 5, 3, 4, 7, 1, 2, 0, 9, 6])


In [14]:
# 查看随机数种子
print(torch.random.initial_seed())
# 设置随机数种子
torch.manual_seed(42)
print(torch.random.initial_seed())

11132552189193573670
42
