In [2]:
import torch
import numpy as np

In [3]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1, tensor1.dtype)

# 使用type方法修改张量的类型
tensor1 = tensor1.type(torch.float32)
print(tensor1, tensor1.dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32


In [4]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1, tensor1.dtype)

# 使用double方法修改张量的类型
tensor1 = tensor1.double()
print(tensor1)
# 使用long方法修改张量的类型
tensor1 = tensor1.long()
print(tensor1, tensor1.dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3]) torch.int64


In [5]:
# 使用numpy()方法将Tensor转换为ndarray，共享内存
tensor1 = torch.rand(3, 2)
numpy_array = tensor1.numpy()
print(tensor1)
print(numpy_array)
print(type(tensor1), type(numpy_array))
print()
tensor1[:, 0] = 4
print(tensor1)
print(numpy_array)
print()

# 使用copy()方法避免共享内存
numpy_array = tensor1.numpy().copy()
tensor1[:, 0] = -1
print(tensor1)
print(numpy_array)

tensor([[0.8935, 0.6685],
        [0.5136, 0.0156],
        [0.9124, 0.9552]])
[[0.8935395  0.6684771 ]
 [0.5135855  0.015634  ]
 [0.91241175 0.9551565 ]]
<class 'torch.Tensor'> <class 'numpy.ndarray'>

tensor([[4.0000, 0.6685],
        [4.0000, 0.0156],
        [4.0000, 0.9552]])
[[4.        0.6684771]
 [4.        0.015634 ]
 [4.        0.9551565]]

tensor([[-1.0000,  0.6685],
        [-1.0000,  0.0156],
        [-1.0000,  0.9552]])
[[4.        0.6684771]
 [4.        0.015634 ]
 [4.        0.9551565]]


In [6]:
# 使用from_numpy()方法将ndarray转换为Tensor，共享内存
numpy_array = np.random.randn(3)
tensor1 = torch.from_numpy(numpy_array)
print(numpy_array)
print(tensor1)
print()
numpy_array[0] = 100
print(numpy_array)
print(tensor1)
print()

# 使用copy()方法避免共享内存
tensor1 = torch.from_numpy(numpy_array.copy())
numpy_array[0] = -1
print(numpy_array)
print(tensor1)

[0.82753219 1.0355411  0.60889428]
tensor([0.8275, 1.0355, 0.6089], dtype=torch.float64)

[100.           1.0355411    0.60889428]
tensor([100.0000,   1.0355,   0.6089], dtype=torch.float64)

[-1.          1.0355411   0.60889428]
tensor([100.0000,   1.0355,   0.6089], dtype=torch.float64)


In [7]:
# 使用torch.tensor()将ndarray转换为Tensor
numpy_array = np.random.randn(3)
tensor1 = torch.tensor(numpy_array)
print(numpy_array)
print(tensor1)
print()
numpy_array[0] = 100
print(numpy_array)
print(tensor1)

[-1.12817001  0.23041144 -1.75729573]
tensor([-1.1282,  0.2304, -1.7573], dtype=torch.float64)

[100.           0.23041144  -1.75729573]
tensor([-1.1282,  0.2304, -1.7573], dtype=torch.float64)


In [8]:
tensor1 = torch.tensor(1)
print(tensor1)
print(tensor1.item())

tensor(1)
1
