In [2]:
import torch
import numpy as np

In [8]:
tensor1 = torch.randint(1, 9, (2, 3))
print(tensor1)
print(tensor1 + 10)
print()

# add()，不修改原数据
print(tensor1.add(10))
print(tensor1)
print()

# add_()，修改原数据
print(tensor1.add_(10))
print(tensor1)

tensor([[3, 7, 2],
        [8, 1, 2]])
tensor([[13, 17, 12],
        [18, 11, 12]])

tensor([[13, 17, 12],
        [18, 11, 12]])
tensor([[3, 7, 2],
        [8, 1, 2]])

tensor([[13, 17, 12],
        [18, 11, 12]])
tensor([[13, 17, 12],
        [18, 11, 12]])


In [9]:
tensor1 = torch.tensor([1, 2, 3])
print(-tensor1)
print()

print(tensor1.neg())
print(tensor1)
print()

print(tensor1.neg_())
print(tensor1)

tensor([-1, -2, -3])

tensor([-1, -2, -3])
tensor([1, 2, 3])

tensor([-1, -2, -3])
tensor([-1, -2, -3])


In [10]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1**2)
print()

print(tensor1.pow(2))
print(tensor1)
print()

print(tensor1.pow_(2))
print(tensor1)

tensor([1, 4, 9])

tensor([1, 4, 9])
tensor([1, 2, 3])

tensor([1, 4, 9])
tensor([1, 4, 9])


In [11]:
tensor1 = torch.tensor([1.0, 2.0, 3.0])
print(tensor1.sqrt())
print(tensor1)
print()

print(tensor1.sqrt_())
print(tensor1)

tensor([1.0000, 1.4142, 1.7321])
tensor([1., 2., 3.])

tensor([1.0000, 1.4142, 1.7321])
tensor([1.0000, 1.4142, 1.7321])


In [12]:
tensor1 = torch.tensor([1.0, 2.0, 3.0])
print(2.71828183**tensor1)
print()

print(tensor1.exp())
print(tensor1)
print()

print(tensor1.exp_())
print(tensor1)

tensor([ 2.7183,  7.3891, 20.0855])

tensor([ 2.7183,  7.3891, 20.0855])
tensor([1., 2., 3.])

tensor([ 2.7183,  7.3891, 20.0855])
tensor([ 2.7183,  7.3891, 20.0855])


In [13]:
tensor1 = torch.tensor([1.0, 2.0, 3.0])
print(tensor1.log())
print(tensor1)
print()

print(tensor1.log_())
print(tensor1)

tensor([0.0000, 0.6931, 1.0986])
tensor([1., 2., 3.])

tensor([0.0000, 0.6931, 1.0986])
tensor([0.0000, 0.6931, 1.0986])


In [14]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[1, 2], [3, 4]])
print(tensor1 * tensor2)
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


In [15]:
# 2维矩阵的矩阵乘法
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(tensor1)
print(tensor2)
print(tensor1.mm(tensor2))
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))
print()

# 3维张量的矩阵乘法
tensor1 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[6, 5, 4], [3, 2, 1]]])
tensor2 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[6, 5], [4, 3], [2, 1]]])
print(tensor1)
print(tensor2)
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[6, 5, 4],
         [3, 2, 1]]])
tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[6, 5],
         [4, 3],
         [2, 1]]])
tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])
tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])


In [3]:
X = torch.randint(1, 9, (3, 2, 4))
Y = torch.randint(1, 9, (3, 4, 1))
print(id(X))
X = X @ Y
print(id(X), end="\n\n")

139810042280144
139810042280224



In [4]:
X = torch.randint(1, 9, (3, 2, 4))
Y = torch.randint(1, 9, (3, 4, 1))
print(id(X))
X[:] = X @ Y
print(id(X))

139810042276864
139810042276864
