In [1]:
import torch
import numpy as np

In [2]:
tensor1 = torch.randint(1, 9, (3, 2, 4))
tensor1 = tensor1.float()
print(tensor1)
print()

# sum() 求和
print("求和")
print(tensor1.sum())
print("按第0个维度求和")
print(tensor1.sum(dim=0))
print()

# mean() 求均值)
print("求均值")
print(tensor1.mean())
print("按第1个维度求均值")
print(tensor1.mean(dim=1))
print()

# max() 求最大值
print("求最大值")
print(tensor1.max())
print("按第2个维度求最大值与索引")
print(tensor1.max(dim=2))
print()

# argmin() 求最小值索引
print("求最小值索引")
print(tensor1.argmin())
print()

# std() 求标准差
print("求标准差")
print(tensor1.std())
print()

# unique() 去重
print("去重")
print(tensor1.unique())
print()

# sort() 排序
print("排序")
print(tensor1.sort())

tensor([[[5., 1., 6., 4.],
         [2., 7., 8., 1.]],

        [[7., 6., 8., 7.],
         [1., 5., 6., 2.]],

        [[7., 1., 4., 4.],
         [7., 7., 5., 6.]]])

求和
tensor(117.)
按第0个维度求和
tensor([[19.,  8., 18., 15.],
        [10., 19., 19.,  9.]])

求均值
tensor(4.8750)
按第1个维度求均值
tensor([[3.5000, 4.0000, 7.0000, 2.5000],
        [4.0000, 5.5000, 7.0000, 4.5000],
        [7.0000, 4.0000, 4.5000, 5.0000]])

求最大值
tensor(8.)
按第2个维度求最大值与索引
torch.return_types.max(
values=tensor([[6., 8.],
        [8., 6.],
        [7., 7.]]),
indices=tensor([[2, 2],
        [2, 2],
        [0, 0]]))

求最小值索引
tensor(1)

求标准差
tensor(2.3831)

去重
tensor([1., 2., 4., 5., 6., 7., 8.])

排序
torch.return_types.sort(
values=tensor([[[1., 4., 5., 6.],
         [1., 2., 7., 8.]],

        [[6., 7., 7., 8.],
         [1., 2., 5., 6.]],

        [[1., 4., 4., 7.],
         [5., 6., 7., 7.]]]),
indices=tensor([[[1, 3, 0, 2],
         [3, 0, 1, 2]],

        [[1, 0, 3, 2],
         [0, 3, 1, 2]],

        [[1, 2, 3, 0],
