In [1]:
import torch
import numpy as np

In [2]:
tensor1 = torch.randint(1, 9, (3, 5, 4))
print(tensor1)
print()

# 取 第0维第0
print(tensor1[0])
print()

# 取 第0维所有，第1维第1
print(tensor1[:, 1])
print()

# 取 第0维所有，第1维第1，第2维第3
print(tensor1[2, 1, 3])

tensor([[[7, 6, 3, 5],
         [5, 6, 2, 6],
         [3, 8, 8, 6],
         [3, 1, 6, 2],
         [6, 5, 5, 2]],

        [[3, 3, 5, 3],
         [3, 5, 6, 3],
         [6, 8, 7, 3],
         [5, 8, 6, 3],
         [2, 1, 5, 3]],

        [[2, 4, 3, 1],
         [6, 5, 5, 3],
         [5, 7, 8, 8],
         [3, 8, 4, 8],
         [4, 7, 1, 5]]])

tensor([[7, 6, 3, 5],
        [5, 6, 2, 6],
        [3, 8, 8, 6],
        [3, 1, 6, 2],
        [6, 5, 5, 2]])

tensor([[5, 6, 2, 6],
        [3, 5, 6, 3],
        [6, 5, 5, 3]])

tensor(3)


In [3]:
tensor1 = torch.randint(1, 9, (3, 5, 4))
print(tensor1)
print()

# 取 第0维第1到最后
print(tensor1[1:])
print()

# 取 第0维最后，第1维1到3(包含3),第2维0到2(包含2)
print(tensor1[-1:, 1:4, 0:3])
print()

tensor([[[5, 4, 5, 7],
         [8, 5, 4, 5],
         [8, 6, 4, 5],
         [4, 8, 4, 3],
         [1, 6, 6, 8]],

        [[5, 1, 7, 2],
         [5, 8, 1, 2],
         [1, 2, 8, 4],
         [8, 5, 1, 8],
         [1, 2, 3, 1]],

        [[1, 4, 6, 7],
         [7, 5, 3, 8],
         [8, 7, 7, 1],
         [7, 8, 3, 3],
         [1, 4, 6, 1]]])

tensor([[[5, 1, 7, 2],
         [5, 8, 1, 2],
         [1, 2, 8, 4],
         [8, 5, 1, 8],
         [1, 2, 3, 1]],

        [[1, 4, 6, 7],
         [7, 5, 3, 8],
         [8, 7, 7, 1],
         [7, 8, 3, 3],
         [1, 4, 6, 1]]])

tensor([[[7, 5, 3],
         [8, 7, 7],
         [7, 8, 3]]])



In [4]:
tensor1 = torch.randint(1, 9, (3, 5, 4))
print(tensor1)
print()

# 取 第0维第0，第1维第1 和 第0维第1，第1维第2
print(tensor1[[0, 1], [1, 2]])
print()

# 取 第0维第0，第1维第1、2 和 第0维第1，第1维第1、2
print(tensor1[[[0], [1]], [1, 2]])

tensor([[[1, 6, 8, 5],
         [5, 2, 4, 2],
         [5, 2, 2, 1],
         [4, 7, 4, 1],
         [7, 3, 4, 3]],

        [[2, 6, 5, 2],
         [1, 6, 6, 2],
         [1, 3, 1, 2],
         [2, 6, 6, 5],
         [4, 2, 8, 8]],

        [[4, 8, 6, 7],
         [2, 8, 4, 2],
         [6, 4, 2, 3],
         [3, 4, 4, 3],
         [6, 1, 8, 1]]])

tensor([[5, 2, 4, 2],
        [1, 3, 1, 2]])

tensor([[[5, 2, 4, 2],
         [5, 2, 2, 1]],

        [[1, 6, 6, 2],
         [1, 3, 1, 2]]])


In [ ]:
tensor1 = torch.randint(1, 9, (3, 5, 4))
print(tensor1)
print()

# 取 第2维第0大于5的，返回(dim0,dim1)形状的索引
print(tensor1[:, :, 0] > 5)
print(tensor1[tensor1[:, :, 0] > 5])
print()

# 取 第1维第1大于5的，返回(dim0,dim2)形状的索引
mask = tensor1[:, 1, :] > 5
print(mask)
tensor2 = tensor1.permute(0, 2, 1) # 转换维度为(dim0,dim2,dim1)
print(tensor2[mask])
tensor2 = tensor2[mask].permute(1, 0) # 转换维度为(dim1,?)
print(tensor2)
print()

# 取 第1维第1，第2维第2大于5的，返回(dim0)形状的索引
print(tensor1[:, 1, 2] > 5)
print(tensor1[tensor1[:, 1, 2] > 5])