In [1]:
import torch
import numpy as np

In [2]:
tensor1 = torch.randint(1, 9, (2, 3, 6))
print(tensor1)
print(tensor1.transpose(1, 2)) # 交换第1维和第2维

tensor([[[6, 7, 6, 3, 7, 3],
         [4, 7, 5, 1, 8, 4],
         [6, 7, 8, 4, 3, 5]],

        [[1, 6, 8, 6, 6, 3],
         [2, 1, 8, 8, 3, 7],
         [2, 5, 7, 7, 7, 7]]])
tensor([[[6, 4, 6],
         [7, 7, 7],
         [6, 5, 8],
         [3, 1, 4],
         [7, 8, 3],
         [3, 4, 5]],

        [[1, 2, 2],
         [6, 1, 5],
         [8, 8, 7],
         [6, 8, 7],
         [6, 3, 7],
         [3, 7, 7]]])


In [3]:
tensor1 = torch.randint(1, 9, (2, 3, 6))
print(tensor1)
print(tensor1.permute(2, 0, 1)) # (2, 3, 6)->(6, 2, 3)

tensor([[[8, 1, 2, 6, 8, 2],
         [1, 5, 2, 4, 8, 1],
         [5, 7, 8, 1, 1, 4]],

        [[7, 4, 1, 8, 5, 6],
         [1, 3, 7, 1, 4, 6],
         [4, 4, 1, 1, 1, 5]]])
tensor([[[8, 1, 5],
         [7, 1, 4]],

        [[1, 5, 7],
         [4, 3, 4]],

        [[2, 2, 8],
         [1, 7, 1]],

        [[6, 4, 1],
         [8, 1, 1]],

        [[8, 8, 1],
         [5, 4, 1]],

        [[2, 1, 4],
         [6, 6, 5]]])


In [4]:
tensor1 = torch.randint(1, 9, (3, 5, 4))
print(tensor1)
print(tensor1.reshape(6, 10))
print(tensor1.reshape(3, -1))

tensor([[[1, 8, 1, 4],
         [5, 5, 4, 8],
         [1, 3, 6, 2],
         [8, 3, 6, 5],
         [5, 4, 6, 6]],

        [[5, 1, 8, 7],
         [3, 8, 2, 2],
         [7, 8, 6, 7],
         [6, 6, 3, 3],
         [7, 5, 4, 3]],

        [[7, 4, 7, 3],
         [8, 4, 5, 6],
         [3, 2, 6, 8],
         [5, 8, 8, 1],
         [4, 1, 1, 8]]])
tensor([[1, 8, 1, 4, 5, 5, 4, 8, 1, 3],
        [6, 2, 8, 3, 6, 5, 5, 4, 6, 6],
        [5, 1, 8, 7, 3, 8, 2, 2, 7, 8],
        [6, 7, 6, 6, 3, 3, 7, 5, 4, 3],
        [7, 4, 7, 3, 8, 4, 5, 6, 3, 2],
        [6, 8, 5, 8, 8, 1, 4, 1, 1, 8]])
tensor([[1, 8, 1, 4, 5, 5, 4, 8, 1, 3, 6, 2, 8, 3, 6, 5, 5, 4, 6, 6],
        [5, 1, 8, 7, 3, 8, 2, 2, 7, 8, 6, 7, 6, 6, 3, 3, 7, 5, 4, 3],
        [7, 4, 7, 3, 8, 4, 5, 6, 3, 2, 6, 8, 5, 8, 8, 1, 4, 1, 1, 8]])


In [5]:
tensor1 = torch.randint(1, 9, (3, 5, 4))
print(tensor1)
print(tensor1.is_contiguous()) # is_contiguous()判断是否内存连续
print(tensor1.view(-1, 10))

tensor1 = tensor1.T
print(tensor1.is_contiguous()) # is_contiguous()判断是否内存连续
print(tensor1.contiguous().view(-1)) # contiguous()强制内存连续

tensor([[[5, 2, 4, 7],
         [8, 5, 5, 6],
         [5, 5, 1, 2],
         [1, 2, 6, 1],
         [8, 3, 5, 7]],

        [[1, 6, 2, 4],
         [5, 3, 6, 6],
         [6, 6, 2, 2],
         [8, 4, 4, 8],
         [1, 2, 8, 6]],

        [[1, 2, 7, 8],
         [6, 5, 5, 4],
         [4, 6, 8, 7],
         [4, 3, 1, 8],
         [5, 3, 3, 7]]])
True
tensor([[5, 2, 4, 7, 8, 5, 5, 6, 5, 5],
        [1, 2, 1, 2, 6, 1, 8, 3, 5, 7],
        [1, 6, 2, 4, 5, 3, 6, 6, 6, 6],
        [2, 2, 8, 4, 4, 8, 1, 2, 8, 6],
        [1, 2, 7, 8, 6, 5, 5, 4, 4, 6],
        [8, 7, 4, 3, 1, 8, 5, 3, 3, 7]])
False
tensor([5, 1, 1, 8, 5, 6, 5, 6, 4, 1, 8, 4, 8, 1, 5, 2, 6, 2, 5, 3, 5, 5, 6, 6,
        2, 4, 3, 3, 2, 3, 4, 2, 7, 5, 6, 5, 1, 2, 8, 6, 4, 1, 5, 8, 3, 7, 4, 8,
        6, 6, 4, 2, 2, 7, 1, 8, 8, 7, 6, 7])


/tmp/ipykernel_3170845/3479513607.py:6: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3683.)
  tensor1 = tensor1.T


In [6]:
tensor1 = torch.tensor([1, 2, 3, 4, 5])
print(tensor1)
# 在0维上增加一个维度
print(tensor1.unsqueeze(dim=0))
# 在1维上增加一个维度
print(tensor1.unsqueeze(dim=1))
# 在-1维上增加一个维度
print(tensor1.unsqueeze(dim=-1))

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3, 4, 5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])


In [7]:
tensor1 = torch.tensor([1, 2, 3, 4, 5])
print(tensor1.unsqueeze_(dim=0))
print(tensor1.squeeze())

tensor([[1, 2, 3, 4, 5]])
tensor([1, 2, 3, 4, 5])


In [8]:
tensor1 = torch.randint(1, 9, (2, 2, 5))
tensor2 = torch.randint(1, 9, (2, 1, 5))
print(tensor1)
print(tensor2)
print(torch.cat([tensor1, tensor2], dim=1))

tensor([[[7, 1, 5, 1, 8],
         [4, 4, 7, 1, 5]],

        [[7, 6, 1, 5, 8],
         [7, 3, 1, 3, 1]]])
tensor([[[4, 5, 6, 6, 4]],

        [[1, 2, 6, 3, 1]]])
tensor([[[7, 1, 5, 1, 8],
         [4, 4, 7, 1, 5],
         [4, 5, 6, 6, 4]],

        [[7, 6, 1, 5, 8],
         [7, 3, 1, 3, 1],
         [1, 2, 6, 3, 1]]])


In [9]:
torch.manual_seed(42)
tensor1 = torch.randint(1, 9, (3, 1, 5))
tensor2 = torch.randint(1, 9, (3, 1, 5))
print(tensor1)
print(tensor2)
tensor3 = torch.stack([tensor1, tensor2], dim=2)
print(tensor3)
print(tensor3.shape)

tensor([[[7, 4, 5, 7, 3]],

        [[8, 5, 5, 7, 2]],

        [[3, 7, 3, 3, 8]]])
tensor([[[5, 4, 8, 8, 3]],

        [[6, 5, 2, 8, 4]],

        [[6, 6, 2, 8, 4]]])
tensor([[[[7, 4, 5, 7, 3],
          [5, 4, 8, 8, 3]]],


        [[[8, 5, 5, 7, 2],
          [6, 5, 2, 8, 4]]],


        [[[3, 7, 3, 3, 8],
          [6, 6, 2, 8, 4]]]])
torch.Size([3, 1, 2, 5])
