In [2]:
import torch

In [3]:
# 定义数据
x = torch.tensor(10.0)
y = torch.tensor(3.0)
print(x.requires_grad)
print(y.requires_grad)

False
False


In [4]:
w = torch.rand(1,1,requires_grad=True)
b = torch.rand(1,1,requires_grad=True)


In [5]:
# 得到前向传播的输出
z = x * w + b
print(z)
print(z.requires_grad)

tensor([[3.2712]], grad_fn=<AddBackward0>)
True


In [6]:
# 查看是否为叶子节点
print(x.is_leaf)
print(y.is_leaf)
print(w.is_leaf)
print(z.is_leaf)
print(b.is_leaf)

True
True
True
False
True


In [7]:
# 设置损失函数
loss = torch.nn.MSELoss()

# 计算损失
loss_value = loss(z,y.view_as(z))
print(loss_value)
print(loss_value.is_leaf)

tensor(0.0735, grad_fn=<MseLossBackward0>)
False


In [8]:
loss_value.backward()

In [9]:
print(w.grad)
print(b.grad)

tensor([[5.4236]])
tensor([[0.5424]])
